name: base
channels:
  - conda-forge
  - ome
dependencies:
  # - beakerx
  - pip
  - websockify
  - pyimagej
  - omero-py
  - jupyter-server-proxy
  - openjdk=11
  - pip:
    - imjoy==0.11.16
    - imjoy-elfinder==0.1.61
